### ISSUE TITLE
Extra Line Breaks / Recursion Not Functioning?

### ISSUE THREAD

**Issue by puddlecheese** [MediosZ/obsidian-subdivider#1]
Hello!

I just discovered this plugin, and am hooked on the idea. I too am fond of smaller notes, and this plugin is so close to being what I'm looking for in my note migration project.

# Line Breaks
That being said, I have noticed that when subdividing a note, blank line breaks are added. For example:

```
## Linux ^20230425040217AM
### Debian-Based Distributions ^20230425040225AM
- `Obsidian-1116-AMD64-Deb.deb` can be used.
- It may be necessary to right-click the file and open it as a `Software Install`.
```
Will be subdivided as:
```
# Linux ^20230425040217AM

## Debian-Based Distributions ^20230425040225AM

* `Obsidian-1116-AMD64-Deb.deb` can be used.
* It may be necessary to right-click the file and open it as a `Software Install`.
```

This may be adapting single line breaks to adhere to strict line breaks? I tend to use single line breaks, so I find I'm going back through notes to delete the blank breaks.

# Recursive
Maybe I am understanding this wrong. I have tried dividing notes with and without this option enabled, and the result is identical. I assumed this would split:
```
# Heading 1
- text1
## Heading 2
- text2
### Heading 3
- text3
```
Into:
```
Folder 1, containing a file with text1.
- Subfolder 1, containing a file with text2.
- - Sub-sub-folder 1, containing a file with text3
```
?

Maybe I'm confused?

Please let me know if I can supply more information, and thank you for such a great and useful plugin!

Cheers!

**Comment by MediosZ** [comment]
Hi @puddlecheese, so glad you find this plugin useful!

I will take a look at the line breaks, they should not be changed by the plugin.
And it seems that I forget to implement the recursive feature lol

**Comment by MediosZ** [comment]
The line breaks are added when transforming the markdown AST to markdown plain text. I didn't find any easy solution to maintain the line breaks.

**Comment by puddlecheese** [comment]
> The line breaks are added when transforming the markdown AST to markdown plain text. I didn't find any easy solution to maintain the line breaks.
> 
> [Ref documents](https://github.com/syntax-tree/mdast-util-to-markdown?tab=readme-ov-file#join)

Not the end of the world. There are several ways to delete blank lines en masse through other plugin functionality. I appreciate you taking a look!

**Comment by a13ph** [comment]
i've split off the recursion part into #4

**Comment by MediosZ** [comment]
Hi @puddlecheese I figure out how to avoid extra line breaks.
In the settings, I add one option named `Maintain original line breaks` which will do this.
It's a tricky method, so please report unexpected behaviors.
