### ISSUE TITLE
Subdivision does not copy links correctly.

### ISSUE THREAD

**Issue by moonbrew** [MediosZ/obsidian-subdivider#5]
When Subdiviing a file with one heading into a Folder with the heading and the file in it, links such as `[[Latin Vulgate]]` is copied into the new note as `\[\[Latin Vulgate]]`

Seems like this is an error when the new copy is created. 

On a side note, I noticed that the new file has different creation dates as well. Might be better to do a move instead atleast when the delete option is enabled as I don't want to lose all the history I have with the first file. My use case is coverting a file into a folder with the original file as its folder note. Both my folder and the folder notes have the same names.

**Comment by MediosZ** [comment]
Hi, @moonbrew 
I think I've fixed the link error in 9b45480, please try the latest version.

For the second note, for now the new folder is just created from the original file. So in your use case, maybe you can disable the original file deletion and index file creation, then manually move the original file into the folder newly created.
