### ISSUE TITLE
Subdivision Stopping midway

### ISSUE THREAD

**Issue by Nydid** [MediosZ/obsidian-subdivider#6]
With a very big file with many headers and sub headers, the subdivision process stops midway and creates a broken/incomplete tree structure, where some of the files at the end still have headers to subdivide.

**Comment by MediosZ** [comment]
Could you provide the estimated amount of lines of the file you are using?

**Comment by MediosZ** [comment]
I’m having trouble reproducing this bug with a generated markdown file that has 1000 headers and around 4k lines. It seems like there might be some other clues hidden somewhere.
Could you please share the file you tried, but with the actual text replaced with some random words? I suspect that there's some special structure in the file which triggers this error.

**Comment by MediosZ** [comment]
I tried to add " . " to headers and it works. Could you please confirm if this issue still exists with the latest version?

**Comment by MediosZ** [comment]
I still cannot reproduce with the old version(0.1.2). I think a minimal reproducible file would be helpful.
For example, the following file
```
# Header 1 . with stop
Header one
# Header 2 . with stop
Header two
## Header 22 . with stop
Header 22
```
generates
![SCR-20240812-mzby](https://github.com/user-attachments/assets/6fddfd80-2eba-457c-a239-cc01e83b40ff)

Correct me if I miss something.

**Comment by MediosZ** [comment]
This is strange, it works on my machine(macos)
![image](https://github.com/user-attachments/assets/6301e83b-e34f-4fe7-818f-97843c819a85)
And with your file I get:
[tree_log.txt](https://github.com/user-attachments/files/16579213/tree_log.txt)
It seems working.

May I ask your environment?

**Comment by MediosZ** [comment]
Thanks for the details! I also test this case on a Windows machine, it turns out that file names cannot be ended with a space or a period on Windows. See [this document](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming_conventions).

I guess I need to add some restrictions on the names of headers.

**Comment by MediosZ** [comment]
Can you put the text directly on the comments like before so I can test them

**Comment by MediosZ** [comment]
I find this new issue is caused by an error introduced in 19bbf38.
Thanks for helping me find this out!
Please try [v0.1.16](https://github.com/MediosZ/obsidian-subdivider/releases/tag/0.1.6)
