### ISSUE TITLE
Plugin not updating on Obsidian

### ISSUE THREAD

**Issue by Nydid** [MediosZ/obsidian-subdivider#7]
There are multiple commits and a full release (0.1.2) on Github with fixes, altough the Github actions seem to have passed the checks and the plugin does not seem to have any of the fixes.

The plugin shows 0.1.2 in the list :
<img width="565" alt="image" src="https://github.com/user-attachments/assets/2b95c2e8-1295-43b3-9fd0-598ad1497d28">

But the none of the fixes are there : 
- Recursion Depth still shows XXX
<img width="108" alt="image" src="https://github.com/user-attachments/assets/a40afd87-cb2f-41ef-bd43-31ab1aaa49f3">

- Links are still broken
<img width="134" alt="image" src="https://github.com/user-attachments/assets/c6eaaf30-86c2-4bcc-b289-b3390d85c8ab">

Trying to install manually via the .ZIP file on Github still produces the same results.

**Comment by MediosZ** [comment]
Solved
